version: '3.1'

services:

  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
#    image: pbm-django:dev
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: back.settings.settings
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back:/src
#      - static-content:/src/back/static
#      - media-content:/src/back/media
    depends_on:
      - postgres
    ports:
      - 8000:8000

#  redis:
#    image: redis:5-alpine
#    command: redis-server --appendonly yes
#    ports:
#      - 6379
#    volumes:
#      - redis_data:/data
#
#  celery:
#    build:
#      context: .
#      dockerfile: docker/django/Dockerfile
#    command: bash -c "
#      celery -A back.celery_tasks worker --beat -l info -c 1 -S redbeat.RedBeatScheduler"
#    volumes:
#      - ./back:/src
#    env_file: .env
#    depends_on:
#      - redis
#      - postgres
#
#  mailcatcher:
#    image: dockage/mailcatcher:0.7.1
#    ports:
#      - 1080:1080
#      - 1025:1025

volumes:
  postgres_data:
#  redis_data:
#  static-content:
#  media-content:
