# Generated by Django 3.2.12 on 2024-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('stuff', 'Stuff'), ('regular_user', 'Regular User')], default='regular_user', max_length=20),
        ),
    ]
