# Generated by Django 3.2.12 on 2024-12-20 10:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=20, verbose_name='IP Address')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_login_success', models.BooleanField(default=False, verbose_name='Success')),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Login Log',
                'verbose_name_plural': 'Dashboard Login Logs',
            },
        ),
    ]
